package app

import (
	"encoding/json"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// ── Compose template ─────────────────────────────────────────────────────────
//
// Docker port binding per IP — dual-stack needs separate entries:
//   "192.168.1.100:8000:80"   ← IPv4
//   "[fe80::1]:9000:443"      ← IPv6
//
// Iface "lo" → 127.0.0.1 + ::1 (localhost only)
// Iface "eth0" → real IPs from that interface

var composeTmpl = template.Must(template.New("compose").Parse(`# Auto-generated by frankenphp-manager — {{.Name}} (PHP {{.PHPVer}})
services:
  frankenphp:
    image: dunglas/frankenphp:php{{.PHPVer}}-alpine
    container_name: frankenphp-{{.Name}}
    restart: unless-stopped
    ports:
      {{- range .PortBindings}}
      - "{{.}}"
      {{- end}}
    volumes:
      - {{.Dir}}:/app
      - ./Caddyfile:/etc/caddy/Caddyfile
      - fpm-data:/data
      {{- if ne .HTTPMode "http"}}
      - fpm-certs:/data/caddy
      {{- end}}
    environment:
      {{- if eq .HTTPMode "http"}}
      - SERVER_NAME=:80
      {{- else if eq .HTTPMode "selfsigned"}}
      - SERVER_NAME=localhost
      {{- else}}
      - SERVER_NAME={{.Domain}}
      {{- end}}
      {{- if .DBName}}
      - DATABASE_URL=mysql://{{.MySQLUser}}:{{.MySQLPass}}@frankenphp-mysql:3306/{{.DBName}}
      {{- end}}
      {{- if .UseRedis}}
      - REDIS_HOST=frankenphp-redis
      - REDIS_PORT=6379
      {{- end}}
    networks:
      - frankenphp-net

volumes:
  fpm-data:
  {{- if ne .HTTPMode "http"}}
  fpm-certs:
  {{- end}}

networks:
  frankenphp-net:
    external: true
`))

// ── Caddyfile templates ──────────────────────────────────────────────────────

var caddyHTTPTmpl = template.Must(template.New("caddy-http").Parse(`{
	auto_https off
}

:80 {
	root * /app
	php_server
	log { output stdout format json }
}
`))

var caddySelfSignedTmpl = template.Must(template.New("caddy-selfsigned").Parse(`{
	auto_https disable_redirects
}

:80 {
	root * /app
	php_server
	log { output stdout format json }
}

:443 {
	tls internal
	root * /app
	php_server
	log { output stdout format json }
}
`))

var caddyACMETmpl = template.Must(template.New("caddy-acme").Parse(`{
	email {{.ACMEEmail}}
}

{{.Domain}} {
	root * /app
	php_server
	log { output stdout format json }
}
`))

// ── Template data ────────────────────────────────────────────────────────────

type tplData struct {
	*Project
	MySQLUser    string
	MySQLPass    string
	TLSPort      string
	PortBindings []string // generated: ["127.0.0.1:8000:80", "[::1]:9000:443"]
}

// ── Generate compose + caddyfile ─────────────────────────────────────────────

func GenerateProject(p *Project, c *Config) error {
	dir := ProjectDir(p.Name)
	if err := os.MkdirAll(dir, 0700); err != nil {
		return err
	}

	if p.HTTPMode == "" {
		p.HTTPMode = "http"
	}

	// Resolve interface → IPs
	if p.Iface == "" {
		p.Iface = "lo"
	}
	ipv4, ipv6, err := ResolveInterface(p.Iface)
	if err != nil {
		return fmt.Errorf("interface %q: %w", p.Iface, err)
	}
	p.BindIPv4 = ipv4
	p.BindIPv6 = ipv6

	// TLS port = HTTP port + 1000
	tlsPort := addPort(p.Port, 1000)

	// Build port bindings — one entry per IP
	bindings := portBindings(p, tlsPort)

	data := tplData{
		Project:      p,
		MySQLUser:    c.MySQLUser,
		MySQLPass:    c.MySQLPass,
		TLSPort:      tlsPort,
		PortBindings: bindings,
	}

	// docker-compose.yml
	f, err := os.Create(filepath.Join(dir, "docker-compose.yml"))
	if err != nil {
		return err
	}
	defer f.Close()
	if err := composeTmpl.Execute(f, data); err != nil {
		return err
	}

	// Caddyfile
	cf, err := os.Create(filepath.Join(dir, "Caddyfile"))
	if err != nil {
		return err
	}
	defer cf.Close()

	switch p.HTTPMode {
	case "selfsigned":
		return caddySelfSignedTmpl.Execute(cf, p)
	case "acme":
		return caddyACMETmpl.Execute(cf, p)
	default:
		return caddyHTTPTmpl.Execute(cf, p)
	}
}

// ── Port binding generation ──────────────────────────────────────────────────

func portBindings(p *Project, tlsPort string) []string {
	var bindings []string

	httpBind := fmt.Sprintf("%s:%s:80", p.BindIPv4, p.Port)
	bindings = append(bindings, httpBind)

	if p.BindIPv6 != "" && p.BindIPv6 != p.BindIPv4 {
		ipv6Bind := fmt.Sprintf("[%s]:%s:80", p.BindIPv6, p.Port)
		bindings = append(bindings, ipv6Bind)
	}

	if p.HTTPMode != "http" {
		tlsBind := fmt.Sprintf("%s:%s:443", p.BindIPv4, tlsPort)
		bindings = append(bindings, tlsBind)
		if p.BindIPv6 != "" && p.BindIPv6 != p.BindIPv4 {
			ipv6TLSBind := fmt.Sprintf("[%s]:%s:443", p.BindIPv6, tlsPort)
			bindings = append(bindings, ipv6TLSBind)
		}
	}

	return bindings
}

// ── Interface detection ──────────────────────────────────────────────────────

// ResolveInterface returns the first IPv4 and IPv6 addresses on the given interface.
// Special cases:
//
//	"lo"  → 127.0.0.1, ::1
//	"any" → 0.0.0.0, [::]
func ResolveInterface(name string) (ipv4, ipv6 string, err error) {
	switch name {
	case "any", "all", "*":
		return "0.0.0.0", "[::]", nil
	}

	iface, err := net.InterfaceByName(name)
	if err != nil {
		return "", "", fmt.Errorf("interface not found: %w", err)
	}

	addrs, err := iface.Addrs()
	if err != nil {
		return "", "", fmt.Errorf("list addresses: %w", err)
	}

	for _, addr := range addrs {
		var ip net.IP
		switch v := addr.(type) {
		case *net.IPNet:
			ip = v.IP
		case *net.IPAddr:
			ip = v.IP
		}
		if ip == nil {
			continue
		}
		if ip.To4() != nil && ipv4 == "" {
			ipv4 = ip.String()
		} else if ip.To4() == nil && ip.IsLinkLocalUnicast() == false && ipv6 == "" {
			// skip link-local (fe80::) for binding — use global unicast
			ipv6 = ip.String()
		} else if ip.To4() == nil && ip.IsLinkLocalUnicast() && ipv6 == "" {
			// fallback to link-local if no global
			ipv6 = ip.String()
		}
	}

	if ipv4 == "" && ipv6 == "" {
		return "", "", fmt.Errorf("no addresses on interface %s", name)
	}
	if ipv4 == "" {
		ipv4 = ipv6 // fallback
	}

	return ipv4, ipv6, nil
}

// ListInterfaces returns available network interface names.
func ListInterfaces() ([]string, error) {
	ifaces, err := net.Interfaces()
	if err != nil {
		return nil, err
	}
	var names []string
	for _, iface := range ifaces {
		if iface.Flags&net.FlagLoopback != 0 {
			names = append(names, iface.Name+" (loopback)")
		} else {
			names = append(names, iface.Name)
		}
	}
	return names, nil
}

// DefaultInterface returns the first non-loopback interface name, or "lo".
func DefaultInterface() string {
	ifaces, err := net.Interfaces()
	if err != nil {
		return "lo"
	}
	for _, iface := range ifaces {
		if iface.Flags&net.FlagLoopback != 0 {
			continue
		}
		if iface.Flags&net.FlagUp == 0 {
			continue
		}
		return iface.Name
	}
	return "lo"
}

// DescribeInterface returns a human-readable summary of an interface's addresses.
func DescribeInterface(name string) string {
	ipv4, ipv6, err := ResolveInterface(name)
	if err != nil {
		return fmt.Sprintf("%s (error: %v)", name, err)
	}
	parts := []string{name}
	if ipv4 != "" {
		parts = append(parts, "ipv4="+ipv4)
	}
	if ipv6 != "" {
		parts = append(parts, "ipv6="+ipv6)
	}
	return strings.Join(parts, " ")
}

// ── Helpers ──────────────────────────────────────────────────────────────────

func addPort(port string, offset int) string {
	var n int
	fmt.Sscanf(port, "%d", &n)
	return fmt.Sprintf("%d", n+offset)
}

func contains(s, sub string) bool {
	for i := 0; i <= len(s)-len(sub); i++ {
		if s[i:i+len(sub)] == sub {
			return true
		}
	}
	return false
}

// ── Auto-detection ───────────────────────────────────────────────────────────

func DetectPHP(dir string) string {
	data, err := os.ReadFile(filepath.Join(dir, "composer.json"))
	if err != nil {
		return ""
	}
	s := string(data)
	for _, v := range SupportedPHP {
		if contains(s, v) {
			return v
		}
	}
	return ""
}

func DetectFramework(dir string) string {
	checks := []struct {
		file, name string
	}{
		{"artisan", "Laravel"}, {"bin/console", "Symfony"},
		{"wp-config.php", "WordPress"}, {"vendor/autoload.php", "Composer"},
		{"index.php", "PHP"},
	}
	for _, c := range checks {
		if _, err := os.Stat(filepath.Join(dir, c.file)); err == nil {
			return c.name
		}
	}
	return ""
}

func NextPort(c *Config) string {
	used := map[string]bool{}
	for _, p := range c.Projects {
		used[p.Port] = true
	}
	for port := 8000; port < 9000; port++ {
		ps := fmt.Sprintf("%d", port)
		if !used[ps] {
			return ps
		}
	}
	return "8000"
}

func RemoveProjectDir(name string) error {
	return os.RemoveAll(ProjectDir(name))
}

func MarshalJSON(v any) string {
	b, _ := json.MarshalIndent(v, "", "  ")
	return string(b)
}
