name: Build and Release

on:
  workflow_dispatch:
  release:
    types: [published, prereleased]

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}

    steps:
      - name: Get version
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Detected version: $VERSION"

      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go environment
        uses: actions/setup-go@v6
        with:
          go-version: '1.23'
          check-latest: true

      - name: Generate Output Names
        run: |
          BINARY_NAME="frankenphp-manager_${{ matrix.goos }}_${{ matrix.goarch }}"
          PACKAGE_DIR_NAME="frankenphp-manager_${{ matrix.goos }}_${{ matrix.goarch }}"
          ARCHIVE_NAME="frankenphp-manager_${{ matrix.goos }}_${{ matrix.goarch }}"
          
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV
          echo "PACKAGE_DIR_NAME=$PACKAGE_DIR_NAME" >> $GITHUB_ENV
          echo "ARCHIVE_NAME=$ARCHIVE_NAME" >> $GITHUB_ENV

      - name: Backend Build
        run: |
          go build -ldflags "-s -w -X 'main.version=${{ env.VERSION }}' -X 'main.goVersion=$(go version)' -X 'main.gitHash=$(git rev-parse HEAD)' -X 'main.buildTime=$(date -u +'%Y-%m-%dT%H:%M:%SZ')'" -o ${{ env.BINARY_NAME }} cmd/server/main.go

      - name: Create Archive
        run: |
          rm -rf ${{ env.PACKAGE_DIR_NAME }}
          mkdir -p ${{ env.PACKAGE_DIR_NAME }}
          
          cp ${{ env.BINARY_NAME }} ${{ env.PACKAGE_DIR_NAME }}/frankenphp-manager
          cp scripts/install.sh ${{ env.PACKAGE_DIR_NAME }}/
          cp scripts/uninstall.sh ${{ env.PACKAGE_DIR_NAME }}/
          cp scripts/frankenphp-manager-service.sh ${{ env.PACKAGE_DIR_NAME }}/
          cp README.md ${{ env.PACKAGE_DIR_NAME }}/
          cp LICENSE ${{ env.PACKAGE_DIR_NAME }}/
          
          tar -czvf ${{ env.ARCHIVE_NAME }}.tar.gz ${{ env.PACKAGE_DIR_NAME }}/

      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.ARCHIVE_NAME }}
          path: ${{ env.ARCHIVE_NAME }}.tar.gz
          if-no-files-found: ignore

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./${{ env.ARCHIVE_NAME }}.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
